// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertieForLanguages.DataContext.Sqlite.Data;

#nullable disable

namespace PropertieForLanguages.DataContext.Sqlite.Migrations
{
    [DbContext(typeof(VocabularyContext))]
    partial class VocabularyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PropertieForLanguages.DataContext.Sqlite.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "en",
                            Term = "Apple",
                            Translation = "Яблуко"
                        },
                        new
                        {
                            Id = 2,
                            Language = "en",
                            Term = "Table",
                            Translation = "Стіл"
                        },
                        new
                        {
                            Id = 3,
                            Language = "de",
                            Term = "Buch",
                            Translation = "Книга"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
